### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by SalmonDE** [SalmonDE/GuessTheNumber#1]
- [x] [[Completed]](https://github.com/SalmonCraftPE/GuessTheNumber/commit/470f87db05733ddf6b011bac41bfa198a805c19d) Own delayed task for the waiting timer, or TimerAPI
- [x] [[Completed]](https://github.com/SalmonCraftPE/GuessTheNumber/commit/f3e7e9da94886a207d50fd45b54de7ca733a1573) Json Update
- [x] Create language files for German
- [x] Rewrite the language mess and most code
- [x] [[Completed]](https://github.com/SalmonGER/GuessTheNumber/commit/a1db4ce08afedcca271ad0decd3345d8d1fb180b) MSG not defined in NumberTask

**Comment by SalmonGER** [comment]
And merge it into SCraftPE-MH
lol.

**Comment by Aericio** [comment]
Leeenguage file almost done q.q Its painful

**Comment by Aericio** [comment]
Also I might not even use it, these kids suck at math xd

**Comment by SalmonDE** [comment]
But the first thing is guessing not mathing (I'm sure you can't say it like that)

**Comment by SalmonDE** [comment]
Should I make the repository private? Like I'm a noob coder and will probably code like a 2 year old speaks business English

**Comment by Adam1609** [comment]
Can I participate in translate into Vietnamese?

**Comment by Aericio** [comment]
If you want to, make a pull request.

**Comment by SalmonDE** [comment]
I think I'll use for the language files json. I'm json addicted lmao.

**Comment by SalmonDE** [comment]
@Adam1609 Sure, when I'm done you can create a language file and add it with a pull request. :)
